name: Test1
on: push
#to add multiple triggers on: [push, workflow_dispatch]
#to add activities and event filters
#on:
  #pull_request:
    #types: [opened, edited]
    #types:
       - opened
       - edited
  #workflow_dispatch:
#Event branch filters
  #push:
    #branches:
       #- main
       #- 'dev-*'  --> dev-new, dev-new-one
       #= 'feat/**' --> feat/one, feat/one/two
  
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Restore Dependecies
        run: dotnet restore AspNetCoreTests/AspNetCoreTests.Web/AspNetCoreTests.Web.csproj
      - name: Build
        run: dotnet build "./AspNetCoreTests/AspNetCoreTests.Web" --configuration Release --no-restore
        #run: dotnet build --configuration ${{ env.BuildConfiguration }}
      - name: UnitTest
        run: dotnet test "./AspNetCoreTests/AspNetCoreTests.UnitTests" --no-restore --verbosity normal
      - name: IntegrationTest
        run: dotnet test "./AspNetCoreTests/AspNetCoreTests.IntegrationTests" --no-restore --verbosity normal         
      - name: Publish application
        run: dotnet publish "./AspNetCoreTests" -c Release -o myApp
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: my-artifact
         path: "./AspNetCoreTests" 
  Job2:
    needs: Publish
    #MULTIPLE JOBS DEPENDENCY- needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello!"
    
        
    
